language: rust
sudo: required
dist: trusty
rust: stable
services:
  - docker

before_install:
  - docker version
  - apt-cache madison docker-engine
  - sudo apt-get -o Dpkg::Options::="--force-confnew" install -y docker-engine

install:
  - npm install jshint
  - sudo pip install pygments
script:
  - find static/ -iname "*.js" | xargs jshint
  - cargo build
  - sh docker/build.sh
  - cargo test

notifications:
  email:
    on_success: never
