language: rust
sudo: required
dist: trusty
rust: stable
services:
  - docker

install:
  - npm install jshint
  - sudo pip install pygments
script:
  - find static/ -iname "*.js" | xargs jshint
  - cargo build
  - sh docker/build.sh
  - cargo test

notifications:
  email:
    on_success: never
