# Playbot's (default) configuration file

nick = "playbot-rs"
#password = "1234"
server = "irc.mozilla.org"
channels = ["#rust"]
triggers = [
    ">>",
    "playbot-rs ",
    "playbot-rs,",
    "playbot-rs:"
]
